### ISSUE TITLE
RMM issues

### ISSUE THREAD

**Issue by hoonjinn** [hyunsooseol/snowRMM#10]
Dear Dr. Seol,

I hope you are doing well and I always appreciate your amazing works in Jamovi ecology.

I have a quick question about the Rasch Mixture model.

Even though I use the same dataset and enter the same conditions (e.g., class number: 3,  step:1 - dichotomous data type), the information criteria values are substantially changed (i.e., sometimes, the final model is changed) whenever I try to execute the model. I might be wrong, but could you explain why it happens?

Thank you,

Best,
Hoonjin

**Comment by hyunsooseol** [comment]
Hi Hoonjin

Thanks for your question.  the issues that you asked me is involved in , for example, set seed in R.  If we randomly select some observations for any task in  any statistical software it results in different values all the time and this happens because of randomization. The use of set. seed is to make sure that we get the same results for randomization. 

But, I did not use set seed option in jamovi. this is not the problem in the result of Rasch mixture model. Just report one of the results that you try, say class 3, step 1.

Cheers
Seol

**Comment by hoonjinn** [comment]
Hello Dr. Seol,

Thanks for your prompt response! It was really helpful and I try to set a seed number to get consistent IC values! :)

Best,
Hoonjin

**Comment by hoonjinn** [comment]
Hello Dr. Seol,

I have another question while using your RMM modules (it was so comfortable, but helpful tools for researchers). 

I was wondering whether item parameters and fit statistics in RMM are equivalent to those estimated separately from each latent class. Plus, I would like to cite your package in my ongoing manuscripts, and I would be grateful if you let me know the citation for your modules. 

Looking forward to hearing from you.

Thank you,

Best,
Hoonjin

**Comment by hyunsooseol** [comment]
Hi Hoonjin

Could you send me an .omv file as a zip that arise issue. I will take a look at.

For the citation of my module, for example, the analysis was performed by using snowRMM(Seol, 2022) module in jamovi.

Seol, H. (2022). snowRMM: Rasch Mixture Model for jamovi. [jamovi module]. Retrieved from https://github.com/hyunsooseol/snowRMM.

Cheers
Seol
